title: "Philippine Burdeau"
description: "Methane emissions • Produced gas composition • Geostatistics"
url: "https://pburdeau.github.io"
repository: "pburdeau/pburdeau.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: minima
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Appearance
minimal_mistakes_skin: "default"
search: true

# Collections
collections:
  news:
    output: true
    permalink: /news/:name/

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Software"
    url: /software/
  - title: "News"
    url: /news/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# Author box
author:
  name: "Philippine M. Burdeau"
  avatar: "/assets/img/avatar.jpg"
  bio: "Stanford PhD → Boston. Methods for methane emissions and produced gas composition. I build clean, reproducible pipelines for geospatial inference."
  location: "Boston, MA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:pburdeau@stanford.edu"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pburdeau"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/"