title: "Philippine Burdeau"
description: "Methane emissions • Produced gas composition • Geostatistics"
url: "https://pburdeau.github.io"
repository: "pburdeau/pburdeau.github.io"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - .gitignore