title: "Philippine Burdeau"
description: "Methane emissions • Produced gas composition • Geostatistics"
url: "https://pburdeau.github.io"
repository: "pburdeau/pburdeau.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"
search: false

navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Talks"
    url: /talks/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

author:
  name: "Philippine M. Burdeau"
  avatar: "/assets/img/avatar.jpg"
  bio: "Methods for methane emissions and produced gas composition; reproducible geospatial modeling."
  location: "Boston, MA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:pburdeau@stanford.edu"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pburdeau"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/"
markdown: kramdown
kramdown:
  input: GFM
